[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "EasyReflectometryApp"
appname = 'EasyReflectometry'
version = "0.0.5-beta"
description = "Making reflectometry data analysis and modelling easy."
authors = [
    {name = "Andrew R. McCluskey", email = "andrew.mccluskey@ess.eu"}, 
    {name = "Andrew Sazonov"}, 
    {name = "Simon Ward"}
]
maintainers = [
    {name = "Andrew R. McCluskey", email = "andrew.mccluskey@ess.eu"}
]
license = "BSD-3-Clause"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Development Status :: 3 - Alpha"
]
requires-python = ">=3.8,<3.11"
dependencies = [
    'pyobjc-core>=7.1; platform_system == "Darwin"',
    'pyobjc-framework-cocoa>=7.1; platform_system == "Darwin"',
    'matplotlib>=3.4.2',
    'EasyReflectometryLib @ git+https://github.com/easyScience/EasyReflectometryLib.git@no_poetry',
    'easyApp @ git+https://github.com/easyScience/easyApp.git@develop',
    'toml>=0.10.2'
]

[project.optional-dependencies]
dev = [
    'pyinstaller @ git+https://github.com/pyinstaller/pyinstaller.git@develop',
    'pywin32-ctypes>=0.2.0; platform_system == "win32"', 
    'pypiwin32>=223; platform_system == "win32"',
    'pefile>=2022.5.30; platform_system == "win32"',
    'dephell_licenses>=0.1.7'
]

[project.urls]
homepage = 'https://easyreflectometry.org'
documentation = 'https://easyreflectometry.org'

[project.scripts]
EasyReflectometryApp = "EasyReflectometryApp.main:main"

[project.gui-scripts]
EasyReflectometryApp = "EasyReflectometryApp.main:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
include = ['EasyReflectometryApp']

[tool.hatch.build.force-include]
'pyproject.toml' = 'EasyReflectometryApp/pyproject.toml'

[tool.coverage.run]
source = ['EasyReflectometryApp']

