name: Build Snap Image

on: [push, pull_request]

jobs:
  build_snap:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}

  install_test:
    runs-on: ubuntu-latest
    needs: build_snap
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: snap
          path: .
      - name: Install snap
        run: |
            sudo snap install --dangerous *.snap
      - name: Run snap
        run: |
            snap run easyreflectometry &
            sleep 60
            killall easyreflectometry
